### ISSUE TITLE
Line Breaks

### ISSUE THREAD

**Issue by leartpro** [gerardmarquinarubio/ReactTypewriter#17]
Line Breaks are not detected

**Comment by gerardmarquinarubio** [comment]
What do you mean? Escaping a line break with `\n` is not working?

**Comment by gerardmarquinarubio** [comment]
Will close until further information is provided.

**Comment by gerardmarquinarubio** [comment]
@leartpro Just in case I [updated the codesandbox example](https://codesandbox.io/s/react-typewriter-example-mgyclf) to show a line-breaking test. The relevant code is:

```jsx
<div
  style={{
    whiteSpace: "pre"
  }}
>
  <Typewriter text={`Line \n breaks`} loop />
</div>
```

**Comment by leartpro** [comment]
> What do you mean? Escaping a line break with `\n` is not working?

When I use \n, the text is simply output in one line. \n is also not output as text (which is basically correct), but simply has no effect.

**Comment by leartpro** [comment]
Okay, It seems that the fault lies with me. Thanks for the quick feedback
